
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 23.2.0 - arm64
...
